# Generated by Django 4.2.1 on 2023-05-13 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
